pipeline {
        agent any
	options { 
		disableConcurrentBuilds() 
	}
        stages {
                stage('Deploy') {
                        steps {
                                sh 'docker run -i --rm -v $(pwd):/code -v /root/.m2:/root/.m2 maven:3-jdk-8 sh -c "cd /code; mvn clean deploy"'
                        }
                }
        }
}
